SELECT B.FLAVOR
FROM(
    SELECT SHIPMENT_ID,FLAVOR,SUM(A.TOTAL_ORDER) AS TOTAL
    FROM JULY A
    GROUP BY A.FLAVOR
) AS B
JOIN FIRST_HALF C ON C.SHIPMENT_ID = B.SHIPMENT_ID
GROUP BY B.FLAVOR
ORDER BY SUM(C.TOTAL_ORDER+B.TOTAL) DESC
LIMIT 3